### ISSUE TITLE
[Java] Add jdk21 CI

### ISSUE THREAD

**Issue by chaokunyang** [alipay/fury#979]
## Is your feature request related to a problem? Please describe.
Add oracle JDK21 CI

## Describe the solution you'd like
Install JDK21 by:
```yml
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'oracle'
```

WE didn't switch all jdk release to zulu, since oracle jdk is used more frequently.
## Additional context
#976
